NZOMBIES_VARS = NZOMBIES_VARS or {}
NZOMBIES_VARS.SOUND = {}
NZOMBIES_VARS.SOUND.NZ = {}
NZOMBIES_VARS.SOUND.NZ.POWERUPS = {}
NZOMBIES_VARS.SOUND.NZ.ROUND = {}
NZOMBIES_VARS.SOUND.NZ.BOWIE = {}
NZOMBIES_VARS.SOUND.NZ.BOWIE.DRAW = {}
NZOMBIES_VARS.SOUND.NZ.BOWIE.STAB = {}
NZOMBIES_VARS.SOUND.NZ.BOWIE.SWING = {}
NZOMBIES_VARS.SOUND.NZ.BOWIE.DEATHMACHINE = {}
NZOMBIES_VARS.SOUND.NZ.DEATHMACHINE = {}
NZOMBIES_VARS.SOUND.NZ.EASTEREGG = {}
NZOMBIES_VARS.SOUND.NZ.EFFECTS = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.BITE = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.CLOSE = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2 = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.EXPLOSION = {}
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.SPAWN = {}
NZOMBIES_VARS.SOUND.NZ.MACHINES = {}
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE = {}
NZOMBIES_VARS.SOUND.NZ.MONKEY = {}
NZOMBIES_VARS.SOUND.NZ.MONKEY.CYMBALS = {}
NZOMBIES_VARS.SOUND.NZ.MONKEY.MUSIC = {}
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_BOUNCE = {}
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION = {}
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME = {}
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_THROW = {}
NZOMBIES_VARS.SOUND.NZ.PANZER = {}
NZOMBIES_VARS.SOUND.NZ.PANZER.AMBIENT = {}
NZOMBIES_VARS.SOUND.NZ.PANZER.ATTACK = {}
NZOMBIES_VARS.SOUND.NZ.PANZER.CLAW = {}
NZOMBIES_VARS.SOUND.NZ.PANZER.FOOTSTEPS = {}
NZOMBIES_VARS.SOUND.NZ.PANZER.LAND = {}
NZOMBIES_VARS.SOUND.NZ.PANZER.SERVO = {}
NZOMBIES_VARS.SOUND.NZ.PERKS = {}
NZOMBIES_VARS.SOUND.NZ.POWERUPS = {}
NZOMBIES_VARS.SOUND.NZ.RANDOMBOX = {}
NZOMBIES_VARS.SOUND.NZ.ROUND = {}
NZOMBIES_VARS.SOUND.NZ.ZOMBIES = {}
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT = {}
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK = {}
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH = {}
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ELECTROCUTED = {}
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPAWN = {}
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2 = {}

NZOMBIES_VARS.SOUND.NZ.POWERUPS.DEATHMACHINE = "nz/powerups/deathmachine.mp3"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.DOUBLE_POINTS = "nz/powerups/double_points.mp3"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.INSTA_KILL = "nz/powerups/insta_kill.mp3"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.MAX_AMMO = "nz/powerups/max_ammo.mp3"

NZOMBIES_VARS.SOUND.NZ.ROUND.GAME_OVER__1 = "nz/round/game_over_-1.mp3"
NZOMBIES_VARS.SOUND.NZ.ROUND.GAME_OVER_4 = "nz/round/game_over_4.mp3"
NZOMBIES_VARS.SOUND.NZ.ROUND.GAME_OVER_5 = "nz/round/game_over_5.mp3"
NZOMBIES_VARS.SOUND.NZ.ROUND.ROUND__1_PREPARE = "nz/round/round_-1_prepare.mp3"
NZOMBIES_VARS.SOUND.NZ.ROUND.ROUND_END = "nz/round/round_end.mp3"
NZOMBIES_VARS.SOUND.NZ.ROUND.ROUND_START = "nz/round/round_start.mp3"

NZOMBIES_VARS.SOUND.NZ.BOWIE.DRAW.BOWIE_CATCH = "nz/bowie/draw/bowie_catch.wav"
NZOMBIES_VARS.SOUND.NZ.BOWIE.DRAW.BOWIE_START = "nz/bowie/draw/bowie_start.wav"
NZOMBIES_VARS.SOUND.NZ.BOWIE.DRAW.BOWIE_TOSS = "nz/bowie/draw/bowie_toss.wav"
NZOMBIES_VARS.SOUND.NZ.BOWIE.DRAW.BOWIE_TURN = "nz/bowie/draw/bowie_turn.wav"

NZOMBIES_VARS.SOUND.NZ.BOWIE.STAB.BOWIE_STAB_00 = "nz/bowie/stab/bowie_stab_00.wav"
NZOMBIES_VARS.SOUND.NZ.BOWIE.STAB.BOWIE_STAB_01 = "nz/bowie/stab/bowie_stab_01.wav"
NZOMBIES_VARS.SOUND.NZ.BOWIE.STAB.BOWIE_STAB_02 = "nz/bowie/stab/bowie_stab_02.wav"

NZOMBIES_VARS.SOUND.NZ.BOWIE.SWING.BOWIE_SWING_00 = "nz/bowie/swing/bowie_swing_00.wav"
NZOMBIES_VARS.SOUND.NZ.BOWIE.SWING.BOWIE_SWING_01 = "nz/bowie/swing/bowie_swing_01.wav"
NZOMBIES_VARS.SOUND.NZ.BOWIE.SWING.BOWIE_SWING_02 = "nz/bowie/swing/bowie_swing_02.wav"

NZOMBIES_VARS.SOUND.NZ.DEATHMACHINE.LOOP_L_ = "nz/deathmachine/loop_l_.wav"

NZOMBIES_VARS.SOUND.NZ.EASTEREGG.EE_ITEM_GRAB1 = "nz/easteregg/ee_item_grab1.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.EE_ITEM_GRAB2 = "nz/easteregg/ee_item_grab2.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.EE_ITEM_NOGRAB1 = "nz/easteregg/ee_item_nograb1.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.EE_ITEM_NOGRAB2 = "nz/easteregg/ee_item_nograb2.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.MOTD_BAD = "nz/easteregg/motd_bad.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.MOTD_GOOD = "nz/easteregg/motd_good.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.MOTD_ROUND_01 = "nz/easteregg/motd_round-01.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.MOTD_ROUND_02 = "nz/easteregg/motd_round-02.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.MOTD_ROUND_03 = "nz/easteregg/motd_round-03.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.MOTD_ROUND_04 = "nz/easteregg/motd_round-04.wav"
NZOMBIES_VARS.SOUND.NZ.EASTEREGG.MOTD_STANDARD = "nz/easteregg/motd_standard.wav"

NZOMBIES_VARS.SOUND.NZ.EFFECTS.BOARD_SLAM_00 = "nz/effects/board_slam_00.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.BOARD_SLAM_01 = "nz/effects/board_slam_01.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.BOARD_SLAM_02 = "nz/effects/board_slam_02.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.BOARD_SLAM_03 = "nz/effects/board_slam_03.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.BOARD_SLAM_04 = "nz/effects/board_slam_04.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.BOARD_SLAM_05 = "nz/effects/board_slam_05.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.BUY = "nz/effects/buy.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.GONE = "nz/effects/gone.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.PAP_LASER_SHOT = "nz/effects/pap_laser_shot.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.PAP_SHOOT_GLOCK20 = "nz/effects/pap_shoot_glock20.wav"
NZOMBIES_VARS.SOUND.NZ.EFFECTS.REPAIR_CHING = "nz/effects/repair_ching.wav"

NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK.ATTACK_00 = "nz/hellhound/attack/attack_00.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK.ATTACK_01 = "nz/hellhound/attack/attack_01.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK.ATTACK_02 = "nz/hellhound/attack/attack_02.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK.ATTACK_03 = "nz/hellhound/attack/attack_03.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK.ATTACK_04 = "nz/hellhound/attack/attack_04.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK.ATTACK_05 = "nz/hellhound/attack/attack_05.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.ATTACK.ATTACK_06 = "nz/hellhound/attack/attack_06.wav"

NZOMBIES_VARS.SOUND.NZ.HELLHOUND.BITE.BITE_00 = "nz/hellhound/bite/bite_00.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.BITE.BITE_01 = "nz/hellhound/bite/bite_01.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.BITE.BITE_02 = "nz/hellhound/bite/bite_02.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.BITE.BITE_03 = "nz/hellhound/bite/bite_03.wav"

NZOMBIES_VARS.SOUND.NZ.HELLHOUND.CLOSE.CLOSE_00 = "nz/hellhound/close/close_00.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.CLOSE.CLOSE_01 = "nz/hellhound/close/close_01.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.CLOSE.CLOSE_02 = "nz/hellhound/close/close_02.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.CLOSE.CLOSE_03 = "nz/hellhound/close/close_03.wav"

NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2.DEATH0 = "nz/hellhound/death2/death0.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2.DEATH1 = "nz/hellhound/death2/death1.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2.DEATH2 = "nz/hellhound/death2/death2.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2.DEATH3 = "nz/hellhound/death2/death3.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2.DEATH4 = "nz/hellhound/death2/death4.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2.DEATH5 = "nz/hellhound/death2/death5.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DEATH2.DEATH6 = "nz/hellhound/death2/death6.wav"

NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_00 = "nz/hellhound/dist_vox_a/dist_vox_a_00.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_01 = "nz/hellhound/dist_vox_a/dist_vox_a_01.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_02 = "nz/hellhound/dist_vox_a/dist_vox_a_02.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_03 = "nz/hellhound/dist_vox_a/dist_vox_a_03.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_04 = "nz/hellhound/dist_vox_a/dist_vox_a_04.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_05 = "nz/hellhound/dist_vox_a/dist_vox_a_05.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_06 = "nz/hellhound/dist_vox_a/dist_vox_a_06.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_07 = "nz/hellhound/dist_vox_a/dist_vox_a_07.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_08 = "nz/hellhound/dist_vox_a/dist_vox_a_08.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_09 = "nz/hellhound/dist_vox_a/dist_vox_a_09.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_10 = "nz/hellhound/dist_vox_a/dist_vox_a_10.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.DIST_VOX_A.DIST_VOX_A_11 = "nz/hellhound/dist_vox_a/dist_vox_a_11.wav"

NZOMBIES_VARS.SOUND.NZ.HELLHOUND.EXPLOSION.EXP0 = "nz/hellhound/explosion/exp0.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.EXPLOSION.EXP1 = "nz/hellhound/explosion/exp1.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.EXPLOSION.EXP2 = "nz/hellhound/explosion/exp2.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.EXPLOSION.EXP3 = "nz/hellhound/explosion/exp3.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.EXPLOSION.EXP4 = "nz/hellhound/explosion/exp4.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.EXPLOSION.EXP5 = "nz/hellhound/explosion/exp5.wav"

NZOMBIES_VARS.SOUND.NZ.HELLHOUND.SPAWN.PRESPAWN = "nz/hellhound/spawn/prespawn.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.SPAWN.SPAWN_01 = "nz/hellhound/spawn/spawn_01.wav"
NZOMBIES_VARS.SOUND.NZ.HELLHOUND.SPAWN.STRIKE = "nz/hellhound/spawn/strike.wav"

NZOMBIES_VARS.SOUND.NZ.MACHINES.GEN_LOOP_START = "nz/machines/gen_loop_start.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.PAP_READY = "nz/machines/pap_ready.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.PAP_UP = "nz/machines/pap_up.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.POWER_DOWN = "nz/machines/power_down.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.POWER_UP = "nz/machines/power_up.wav"

NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.CHERRY_GET = "nz/machines/jingle/cherry_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.DEADSHOT_GET = "nz/machines/jingle/deadshot_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.DTAP2_GET = "nz/machines/jingle/dtap2_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.DTAP_GET = "nz/machines/jingle/dtap_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.JUGG_GET = "nz/machines/jingle/jugg_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.MULEKICK_GET = "nz/machines/jingle/mulekick_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.PAP_GET = "nz/machines/jingle/pap_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.PHD_GET = "nz/machines/jingle/phd_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.REVIVE_GET = "nz/machines/jingle/revive_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.SPEED_GET = "nz/machines/jingle/speed_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.STAMINUP_GET = "nz/machines/jingle/staminup_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.TOMBSTONE_GET = "nz/machines/jingle/tombstone_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.VULTURE_GET = "nz/machines/jingle/vulture_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.WHOSWHO_GET = "nz/machines/jingle/whoswho_get.wav"
NZOMBIES_VARS.SOUND.NZ.MACHINES.JINGLE.WIDOWSWINE_GET = "nz/machines/jingle/widowswine_get.wav"

NZOMBIES_VARS.SOUND.NZ.MONKEY.HAT1 = "nz/monkey/hat1.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.HAT2 = "nz/monkey/hat2.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.MONKEYSCREAM = "nz/monkey/monkeyscream.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.WIND_MONKEYBOMB = "nz/monkey/wind_monkeybomb.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.CYMBALS.MONK_CYMB_00 = "nz/monkey/cymbals/monk_cymb_00.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.CYMBALS.MONK_CYMB_01 = "nz/monkey/cymbals/monk_cymb_01.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.CYMBALS.MONK_CYMB_02 = "nz/monkey/cymbals/monk_cymb_02.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.CYMBALS.MONK_CYMB_03 = "nz/monkey/cymbals/monk_cymb_03.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.CYMBALS.MONK_CYMB_04 = "nz/monkey/cymbals/monk_cymb_04.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.CYMBALS.MONK_CYMB_M = "nz/monkey/cymbals/monk_cymb_m.wav"

NZOMBIES_VARS.SOUND.NZ.MONKEY.MUSIC.SONG1 = "nz/monkey/music/song1.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.MUSIC.SONG2 = "nz/monkey/music/song2.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.MUSIC.SONG3 = "nz/monkey/music/song3.wav"

NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_BOUNCE.LAND_00 = "nz/monkey/voice_bounce/land_00.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_BOUNCE.LAND_01 = "nz/monkey/voice_bounce/land_01.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_BOUNCE.LAND_02 = "nz/monkey/voice_bounce/land_02.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_BOUNCE.LAND_03 = "nz/monkey/voice_bounce/land_03.wav"

NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_00 = "nz/monkey/voice_explosion/explo_vox_00.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_01 = "nz/monkey/voice_explosion/explo_vox_01.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_02 = "nz/monkey/voice_explosion/explo_vox_02.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_03 = "nz/monkey/voice_explosion/explo_vox_03.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_04 = "nz/monkey/voice_explosion/explo_vox_04.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_05 = "nz/monkey/voice_explosion/explo_vox_05.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_06 = "nz/monkey/voice_explosion/explo_vox_06.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_07 = "nz/monkey/voice_explosion/explo_vox_07.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_08 = "nz/monkey/voice_explosion/explo_vox_08.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_09 = "nz/monkey/voice_explosion/explo_vox_09.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_10 = "nz/monkey/voice_explosion/explo_vox_10.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_EXPLOSION.EXPLO_VOX_11 = "nz/monkey/voice_explosion/explo_vox_11.wav"

NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_00 = "nz/monkey/voice_prime/raise_vox_00.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_01 = "nz/monkey/voice_prime/raise_vox_01.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_02 = "nz/monkey/voice_prime/raise_vox_02.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_03 = "nz/monkey/voice_prime/raise_vox_03.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_04 = "nz/monkey/voice_prime/raise_vox_04.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_05 = "nz/monkey/voice_prime/raise_vox_05.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_06 = "nz/monkey/voice_prime/raise_vox_06.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_07 = "nz/monkey/voice_prime/raise_vox_07.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_08 = "nz/monkey/voice_prime/raise_vox_08.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_09 = "nz/monkey/voice_prime/raise_vox_09.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_10 = "nz/monkey/voice_prime/raise_vox_10.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_PRIME.RAISE_VOX_11 = "nz/monkey/voice_prime/raise_vox_11.wav"

NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_THROW.THROW_00 = "nz/monkey/voice_throw/throw_00.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_THROW.THROW_01 = "nz/monkey/voice_throw/throw_01.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_THROW.THROW_02 = "nz/monkey/voice_throw/throw_02.wav"
NZOMBIES_VARS.SOUND.NZ.MONKEY.VOICE_THROW.THROW_03 = "nz/monkey/voice_throw/throw_03.wav"

NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_ALARM = "nz/panzer/mech_alarm.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_EXPLODE = "nz/panzer/mech_explode.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_FLAMETHROWER_LOOP = "nz/panzer/mech_flamethrower_loop.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_FLAMETHROWER_START = "nz/panzer/mech_flamethrower_start.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_INTRO = "nz/panzer/mech_intro.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_KILLSHOT = "nz/panzer/mech_killshot.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_ROCKET_LOOP = "nz/panzer/mech_rocket_loop.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.MECH_ROCKET_SHOT = "nz/panzer/mech_rocket_shot.wav"

NZOMBIES_VARS.SOUND.NZ.PANZER.AMBIENT.MECH_AMBI_00 = "nz/panzer/ambient/mech_ambi_00.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.AMBIENT.MECH_AMBI_01 = "nz/panzer/ambient/mech_ambi_01.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.AMBIENT.MECH_AMBI_02 = "nz/panzer/ambient/mech_ambi_02.wav"

NZOMBIES_VARS.SOUND.NZ.PANZER.ATTACK.MECH_SWING_00 = "nz/panzer/attack/mech_swing_00.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.ATTACK.MECH_SWING_01 = "nz/panzer/attack/mech_swing_01.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.ATTACK.MECH_SWING_02 = "nz/panzer/attack/mech_swing_02.wav"

NZOMBIES_VARS.SOUND.NZ.PANZER.CLAW.MECH_CLAW_00 = "nz/panzer/claw/mech_claw_00.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.CLAW.MECH_CLAW_01 = "nz/panzer/claw/mech_claw_01.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.CLAW.MECH_CLAW_02 = "nz/panzer/claw/mech_claw_02.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.CLAW.MECH_CLAW_LOOP = "nz/panzer/claw/mech_claw_loop.wav"

NZOMBIES_VARS.SOUND.NZ.PANZER.FOOTSTEPS.MECH_FOOTSTEP_00 = "nz/panzer/footsteps/mech_footstep_00.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.FOOTSTEPS.MECH_FOOTSTEP_01 = "nz/panzer/footsteps/mech_footstep_01.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.FOOTSTEPS.MECH_FOOTSTEP_02 = "nz/panzer/footsteps/mech_footstep_02.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.FOOTSTEPS.MECH_FOOTSTEP_03 = "nz/panzer/footsteps/mech_footstep_03.wav"

NZOMBIES_VARS.SOUND.NZ.PANZER.LAND.MECH_LAND_00 = "nz/panzer/land/mech_land_00.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.LAND.MECH_LAND_01 = "nz/panzer/land/mech_land_01.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.LAND.MECH_LAND_02 = "nz/panzer/land/mech_land_02.wav"

NZOMBIES_VARS.SOUND.NZ.PANZER.SERVO.MECH_SERVO_00 = "nz/panzer/servo/mech_servo_00.wav"
NZOMBIES_VARS.SOUND.NZ.PANZER.SERVO.MECH_SERVO_01 = "nz/panzer/servo/mech_servo_01.wav"

NZOMBIES_VARS.SOUND.NZ.PERKS.BURP = "nz/perks/burp.wav"
NZOMBIES_VARS.SOUND.NZ.PERKS.BUY = "nz/perks/buy.wav"
NZOMBIES_VARS.SOUND.NZ.PERKS.DRINK = "nz/perks/drink.wav"
NZOMBIES_VARS.SOUND.NZ.PERKS.KNUCKLE_00 = "nz/perks/knuckle_00.wav"
NZOMBIES_VARS.SOUND.NZ.PERKS.KNUCKLE_01 = "nz/perks/knuckle_01.wav"
NZOMBIES_VARS.SOUND.NZ.PERKS.OPEN = "nz/perks/open.wav"
NZOMBIES_VARS.SOUND.NZ.PERKS.SMASH = "nz/perks/smash.wav"

NZOMBIES_VARS.SOUND.NZ.POWERUPS.CARPENTER = "nz/powerups/carpenter.wav"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.CARP_LOOP = "nz/powerups/carp_loop.wav"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.FIRE_SALE_ANNOUNCER = "nz/powerups/fire_sale_announcer.wav"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.NUKE = "nz/powerups/nuke.wav"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.POWER_UP_GRAB = "nz/powerups/power_up_grab.wav"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.POWER_UP_SPAWN = "nz/powerups/power_up_spawn.wav"
NZOMBIES_VARS.SOUND.NZ.POWERUPS.ZOMBIE_BLOOD = "nz/powerups/zombie_blood.wav"

NZOMBIES_VARS.SOUND.NZ.RANDOMBOX.ANNOUNCER_TEDDY_ZOMBIES = "nz/randombox/announcer_teddy_zombies.wav"
NZOMBIES_VARS.SOUND.NZ.RANDOMBOX.FIRE_SALE = "nz/randombox/fire_sale.wav"
NZOMBIES_VARS.SOUND.NZ.RANDOMBOX.POOF = "nz/randombox/poof.wav"
NZOMBIES_VARS.SOUND.NZ.RANDOMBOX.RANDOM_BOX_JINGLE = "nz/randombox/random_box_jingle.wav"
NZOMBIES_VARS.SOUND.NZ.RANDOMBOX.TEDDY_BEAR_LAUGH = "nz/randombox/teddy_bear_laugh.wav"

NZOMBIES_VARS.SOUND.NZ.ROUND.DOG_START = "nz/round/dog_start.wav"
NZOMBIES_VARS.SOUND.NZ.ROUND.SPECIAL_ROUND_END = "nz/round/special_round_end.wav"
NZOMBIES_VARS.SOUND.NZ.ROUND.SPECIAL_ROUND_START = "nz/round/special_round_start.wav"

NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_00 = "nz/zombies/ambient/ambient_00.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_01 = "nz/zombies/ambient/ambient_01.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_02 = "nz/zombies/ambient/ambient_02.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_03 = "nz/zombies/ambient/ambient_03.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_04 = "nz/zombies/ambient/ambient_04.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_05 = "nz/zombies/ambient/ambient_05.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_06 = "nz/zombies/ambient/ambient_06.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_07 = "nz/zombies/ambient/ambient_07.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_08 = "nz/zombies/ambient/ambient_08.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_09 = "nz/zombies/ambient/ambient_09.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_10 = "nz/zombies/ambient/ambient_10.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_11 = "nz/zombies/ambient/ambient_11.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_12 = "nz/zombies/ambient/ambient_12.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_13 = "nz/zombies/ambient/ambient_13.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_14 = "nz/zombies/ambient/ambient_14.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_15 = "nz/zombies/ambient/ambient_15.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_16 = "nz/zombies/ambient/ambient_16.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_17 = "nz/zombies/ambient/ambient_17.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_18 = "nz/zombies/ambient/ambient_18.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_19 = "nz/zombies/ambient/ambient_19.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.AMBIENT.AMBIENT_20 = "nz/zombies/ambient/ambient_20.wav"

NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_00 = "nz/zombies/attack/attack_00.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_01 = "nz/zombies/attack/attack_01.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_02 = "nz/zombies/attack/attack_02.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_03 = "nz/zombies/attack/attack_03.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_04 = "nz/zombies/attack/attack_04.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_05 = "nz/zombies/attack/attack_05.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_06 = "nz/zombies/attack/attack_06.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_07 = "nz/zombies/attack/attack_07.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_08 = "nz/zombies/attack/attack_08.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_09 = "nz/zombies/attack/attack_09.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_10 = "nz/zombies/attack/attack_10.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_11 = "nz/zombies/attack/attack_11.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_12 = "nz/zombies/attack/attack_12.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_13 = "nz/zombies/attack/attack_13.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_14 = "nz/zombies/attack/attack_14.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_15 = "nz/zombies/attack/attack_15.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_16 = "nz/zombies/attack/attack_16.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_17 = "nz/zombies/attack/attack_17.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_18 = "nz/zombies/attack/attack_18.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_19 = "nz/zombies/attack/attack_19.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_20 = "nz/zombies/attack/attack_20.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_21 = "nz/zombies/attack/attack_21.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ATTACK.ATTACK_22 = "nz/zombies/attack/attack_22.wav"

NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_00 = "nz/zombies/death/death_00.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_01 = "nz/zombies/death/death_01.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_02 = "nz/zombies/death/death_02.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_03 = "nz/zombies/death/death_03.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_04 = "nz/zombies/death/death_04.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_05 = "nz/zombies/death/death_05.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_06 = "nz/zombies/death/death_06.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_07 = "nz/zombies/death/death_07.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_08 = "nz/zombies/death/death_08.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_09 = "nz/zombies/death/death_09.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.DEATH.DEATH_10 = "nz/zombies/death/death_10.wav"

NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ELECTROCUTED.ELEC_00 = "nz/zombies/electrocuted/elec_00.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ELECTROCUTED.ELEC_01 = "nz/zombies/electrocuted/elec_01.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ELECTROCUTED.ELEC_02 = "nz/zombies/electrocuted/elec_02.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ELECTROCUTED.ELEC_03 = "nz/zombies/electrocuted/elec_03.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ELECTROCUTED.ELEC_04 = "nz/zombies/electrocuted/elec_04.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.ELECTROCUTED.ELEC_05 = "nz/zombies/electrocuted/elec_05.wav"

NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPAWN.ZM_SPAWN_DIRT1 = "nz/zombies/spawn/zm_spawn_dirt1.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPAWN.ZM_SPAWN_DIRT2 = "nz/zombies/spawn/zm_spawn_dirt2.wav"

NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT0 = "nz/zombies/sprint2/sprint0.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT1 = "nz/zombies/sprint2/sprint1.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT2 = "nz/zombies/sprint2/sprint2.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT3 = "nz/zombies/sprint2/sprint3.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT4 = "nz/zombies/sprint2/sprint4.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT5 = "nz/zombies/sprint2/sprint5.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT6 = "nz/zombies/sprint2/sprint6.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT7 = "nz/zombies/sprint2/sprint7.wav"
NZOMBIES_VARS.SOUND.NZ.ZOMBIES.SPRINT2.SPRINT8 = "nz/zombies/sprint2/sprint8.wav"
