
-- Zombies

for k,v in ipairs(NZOMBIES_VARS.MODELS.NZ_ZOMBIE.ZOMBIE_RERIG_ANIMATED) do
    util.PrecacheModel(v)   -- MORE MODELS = MORE LAG IN FIRST SECONDS OF START FIRST ROUND !!!
                            -- BUT DON'T WORRY WHEN PRECACHED ALL NEXT ROUND / GAME WAS START WITH NO LAG
end

util.PrecacheModel(NZOMBIES_VARS.MODELS.NZ_ZOMBIE.ZOMBIE_HELLHOUND)

-- Perk machines
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.CHERRY.CHERRY)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.DEADSHOT.DEADSHOT)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.DOUBLETAP.DOUBLETAP_OFF)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.DOUBLETAP.DOUBLETAP_ON)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.DOUBLETAP2.DOUBLETAP2)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.JUGG.JUGG_OFF)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.JUGG.JUGG_ON)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.MULEKICK.MULEKICK)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.PACKAPUNCH.PACKAPUNCH)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.PHD.PHDFLOPPER)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.REVIVE.REVIVE_OFF)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.REVIVE.REVIVE_ON)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.SPEED.SPEED_OFF)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.SPEED.SPEED_ON)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.STAMINUP.STAMINUP)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.TOMBSTONE.TOMBSTONE)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.VULTURE.VULTUREAID)
util.PrecacheModel(NZOMBIES_VARS.MODELS.ALIG96.PERKS.WHOSWHO.WHOSWHO)

-- Mysery box, teddy and other props
util.PrecacheModel(NZOMBIES_VARS.MODELS.HOFF.PROPS.MYSTERYBOX.BOX)
util.PrecacheModel(NZOMBIES_VARS.MODELS.HOFF.PROPS.MYSTERYBOX.BOX1)
util.PrecacheModel(NZOMBIES_VARS.MODELS.HOFF.PROPS.MYSTERYBOX.BOX2)
util.PrecacheModel(NZOMBIES_VARS.MODELS.HOFF.PROPS.TEDDY_BEAR.TEDDY_BEAR)
util.PrecacheModel(NZOMBIES_VARS.MODELS.NZPROPS.MONKEY_BOMB)
util.PrecacheModel("models/nzprops/power_lever.mdl")
util.PrecacheModel("models/nzprops/power_lever_handle.mdl")
util.PrecacheModel("models/nzprops/power_lever_short.mdl")

-- Powerups
util.PrecacheModel(NZOMBIES_VARS.MODELS.NZPOWERUPS.CARPENTER)
util.PrecacheModel(NZOMBIES_VARS.MODELS.NZPOWERUPS.NUKE)
util.PrecacheModel(NZOMBIES_VARS.MODELS.NZPOWERUPS.X2)
util.PrecacheModel(NZOMBIES_VARS.MODELS.NZPOWERUPS.INSTA)

-- Viewmodels
util.PrecacheModel(NZOMBIES_VARS.MODELS.WEAPONS.C_PERK_BOTTLE)
util.PrecacheModel(NZOMBIES_VARS.MODELS.WEAPONS.C_MONKEY_BOMB)
util.PrecacheModel(NZOMBIES_VARS.MODELS.WEAPONS.C_BOWIE_KNIFE)
util.PrecacheModel(NZOMBIES_VARS.MODELS.WEAPONS.C_REVIVE_MORPHINE)
util.PrecacheModel(NZOMBIES_VARS.MODELS.WEAPONS.C_PACKAPUNCH_ARMS)